import { ASSETS_ICONS } from "../assets-icons";
import { Chain } from "@src/types";
import ROCOCO_LOGO from "/images/rococo.png";
import ASSETHUB_LOGO from "/images/assethub.png";
import PASEO_LOGO from "/images/paseo.svg";

export const SUBTRATE_CHAINS: Chain[] = [
  {
    id: "polkadot",
    name: "Polkadot",
    rpcs: [
      "wss://apps-rpc.polkadot.io",
      "wss://polkadot-rpc.dwellir.com",
      "wss://polkadot-rpc-tn.dwellir.com",
      "wss://rpc.ibp.network/polkadot",
      "wss://rpc.dotters.network/polkadot",
      "wss://1rpc.io/dot",
      "wss://rpc-polkadot.luckyfriday.io",
      "wss://polkadot.public.curie.radiumblock.co/ws",
      "wss://dot-rpc.stakeworld.io",
    ],
    prefix: 0,
    symbol: "DOT",
    decimals: 10,
    explorer: "https://polkadot.subscan.io",
    logo: ASSETS_ICONS["DOT"],
    isTestnet: false,
    isCustom: false,
    type: "wasm",
  },
  {
    id: "acala",
    name: "Acala",
    rpcs: [
      "wss://acala-rpc.dwellir.com",
      "wss://acala-rpc-0.aca-api.network",
      "wss://acala-rpc-1.aca-api.network",
      "wss://acala-rpc-3.aca-api.network/ws",
    ],
    prefix: 10,
    symbol: "ACA",
    decimals: 12,
    explorer: "https://acala.subscan.io",
    logo: ASSETS_ICONS["ACA"],
    isTestnet: false,
    isCustom: false,
    type: "wasm",
  },
  {
    id: "astar",
    name: "Astar",
    rpcs: [
      "wss://astar-rpc.dwellir.com",
      "wss://1rpc.io/astr",
      "wss://rpc.astar.network",
      "wss://astar.public.curie.radiumblock.co/ws",
    ],
    prefix: 5,
    symbol: "ASTR",
    decimals: 18,
    explorer: "https://astar.subscan.io",
    logo: ASSETS_ICONS["ASTR"],
    isTestnet: false,
    isCustom: false,
    type: "wasm",
  },
  {
    id: "kusama",
    name: "Kusama",
    rpcs: [
      "wss://kusama-rpc.dwellir.com",
      "wss://kusama-rpc.polkadot.io",
      "wss://kusama-rpc-tn.dwellir.com",
      "wss://rpc.ibp.network/kusama",
      "wss://rpc.dotters.network/kusama",
      "wss://1rpc.io/ksm",
      "wss://rpc-kusama.luckyfriday.io",
      "wss://kusama.public.curie.radiumblock.co/ws",
      "wss://ksm-rpc.stakeworld.io",
    ],
    prefix: 2,
    symbol: "KSM",
    decimals: 12,
    explorer: "https://kusama.subscan.io",
    logo: ASSETS_ICONS["KSM"],
    isTestnet: false,
    isCustom: false,
    type: "wasm",
  },
  {
    id: "shiden",
    name: "Shiden",
    rpcs: ["wss://shiden-rpc.dwellir.com", "wss://rpc.shiden.astar.network"],
    prefix: 5,
    symbol: "SDN",
    decimals: 18,
    explorer: "https://shiden.subscan.io",
    logo: ASSETS_ICONS["SDN"],
    isTestnet: false,
    isCustom: false,
    type: "wasm",
  },

  // TESTNETS ========================================

  {
    id: "rococo",
    name: "Rococo",
    rpcs: ["wss://rococo-rpc.polkadot.io"],
    prefix: 42,
    symbol: "ROC",
    decimals: 12,
    explorer: "https://rococo.subscan.io",
    logo: ROCOCO_LOGO,
    isTestnet: true,
    isCustom: false,
    type: "wasm",
  },
  {
    id: "rococo-asset-hub",
    name: "Asset Hub (Rococo)",
    rpcs: [
      "wss://rococo-asset-hub-rpc.dwellir.com",
      "wss://rococo-asset-hub-rpc.polkadot.io",
    ],
    prefix: 2,
    symbol: "ROC",
    decimals: 12,
    explorer: "https://assethub-rococo.subscan.io/",
    logo: ASSETHUB_LOGO,
    isTestnet: true,
    isCustom: false,
    type: "wasm",
  },
  {
    id: "mandala",
    name: "Mandala",
    rpcs: ["wss://mandala-tc9-rpc.aca-staging.network"],
    prefix: 42,
    symbol: "ACA",
    decimals: 12,
    explorer: "https://acala-testnet.subscan.io/",
    logo: ASSETS_ICONS["ACA"],
    isTestnet: true,
    isCustom: false,
    type: "wasm",
  },
  {
    id: "shibuya",
    name: "Shibuya",
    rpcs: ["wss://shibuya-rpc.dwellir.com", "wss://rpc.shibuya.astar.network"],
    prefix: 5,
    symbol: "SHB",
    decimals: 18,
    explorer: "https://shibuya.subscan.io",
    logo: ASSETS_ICONS["ASTR"],
    isTestnet: true,
    isCustom: false,
    type: "wasm",
  },
  {
    id: "paseo",
    name: "Paseo",
    rpcs: ["wss://paseo.rpc.amforc.com", "wss://rpc.dotters.network/paseo"],
    prefix: 42,
    symbol: "PAS",
    decimals: 10,
    explorer: "https://paseo.subscan.io",
    logo: PASEO_LOGO,
    isTestnet: true,
    isCustom: false,
    type: "wasm",
  },
  {
    id: "westend",
    name: "Westend",
    rpcs: [
      "wss://westend-rpc.dwellir.com",
      "wss://westend-rpc-tn.dwellir.com",
      "wss://rpc.ibp.network/westend",
      "wss://rpc.dotters.network/westend",
      "wss://rpc-westend.luckyfriday.io",
      "wss://westend-rpc.polkadot.io",
      "wss://westend.public.curie.radiumblock.co/ws",
      "wss://wnd-rpc.stakeworld.io",
    ],
    prefix: 42,
    symbol: "WND",
    decimals: 12,
    explorer: "https://westend.subscan.io",
    logo: ASSETS_ICONS["KSM"],
    isTestnet: true,
    isCustom: false,
    type: "wasm",
  },
];
