import {
  MOONBEAM_ASSETS_MAPPING,
  ASTAR_ASSETS_MAPPING,
  ACALA_ASSETS_MAPPING,
  SHIDEN_ASSETS_MAPPING,
  ROCOCO_ASSET_HUB_ASSETS_MAPPING,
  MOONRIVER_ASSETS_MAPPING,
} from "./chains";

interface IXCM_ASSETS_MAPPING {
  [key: string]: {
    [key: string]: string[];
  };
}

export const XCM_ASSETS_MAPPING: IXCM_ASSETS_MAPPING = {
  "moonbeam-evm": MOONBEAM_ASSETS_MAPPING,
  astar: ASTAR_ASSETS_MAPPING,
  acala: ACALA_ASSETS_MAPPING,
  "moonriver-evm": MOONRIVER_ASSETS_MAPPING,
  shiden: SHIDEN_ASSETS_MAPPING,

  // testnest
  "rococo-asset-hub": ROCOCO_ASSET_HUB_ASSETS_MAPPING,
};
