import { IXCM_MAPPING } from "./interfaces";
import {
  POLKADOT_EXTRINSICS,
  KUSAMA_EXTRINSICS,
  MOONBEAM_EXTRINSICS,
  ACALA_EXTRINSICS,
  ASTAR_EXTRINSICS,
  SHIDEN_EXTRINSICS,
  MOONRIVER_EXTRINSICS,
  ROCOCO_EXTRINSICS,
  ROCOCO_ASSET_HUB_EXTRINSICS,
} from "./chains";

export const XCM_MAPPING: IXCM_MAPPING = {
  polkadot: POLKADOT_EXTRINSICS,
  kusama: KUSAMA_EXTRINSICS,
  "moonbeam-evm": MOONBEAM_EXTRINSICS,
  acala: ACALA_EXTRINSICS,
  astar: ASTAR_EXTRINSICS,
  moonriver: MOONRIVER_EXTRINSICS,
  shiden: SHIDEN_EXTRINSICS,

  // testnest
  rococo: ROCOCO_EXTRINSICS,
  "rococo-asset-hub": ROCOCO_ASSET_HUB_EXTRINSICS,
};
